### ISSUE TITLE
Field 'password' doesn't have a default value

### ISSUE THREAD

**Issue by witwall** [tabulate/tabulate3#1]
need set default password when create user table, or set password field when insert user data.

```
Inserting user 'Anonymous'
PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value -- Unable to execute SQL: <code>INSERT INTO users SET `id` = :id, `name` = :name;</code> Parameters: Array
(
    [id] => 2
    [name] => Anonymous
)
' in /Users/steven/php/tabulate3/src/DB/Database.php:97
Stack trace:
#0 /Users/steven/php/tabulate3/src/DB/Table.php(1009): Tabulate\DB\Database->query('INSERT INTO use...', Array)
#1 /Users/steven/php/tabulate3/src/Commands/UpgradeCommand.php(137): Tabulate\DB\Table->saveRecord(Array)
#2 /Users/steven/php/tabulate3/src/Commands/UpgradeCommand.php(17): Tabulate\Commands\UpgradeCommand->installData(Object(Tabulate\DB\Database))
#3 /Users/steven/php/tabulate3/tabulate(25): Tabulate\Commands\UpgradeCommand->run()
#4 {main}
  thrown in /Users/steven/php/tabulate3/src/DB/Database.php on line 97
```

**Comment by samwilson** [comment]
Yes, quite right! I've actually already fixed this; will commit soon. Stay tuned.

Thanks for reporting! :)
